project_id = "dembele-prof-de-maison"

[auth]
enable_signup = true
minimum_password_length = 10
password_requirements = "lower_upper_letters_digits"

[auth.email]
enable_confirmations = true
double_confirm_changes = true

[functions.chat]
verify_jwt = true
